/asd_rrt_star_planner:
  ros__parameters:
    cost_model_config: /home/i/terrain_radiation_ws/install/radiation_mapping/share/radiation_mapping/config/final_cost_model_v1.json
    cost_profile: balanced
    include_time_penalty: false
    odom_to_map_x: 0.0
    odom_to_map_y: 0.0
    odom_to_map_yaw: 0.0
    radiation_input_max: 100.0
    radiation_input_mode: normalized_occupancy
    terrain_input_max: 100.0
    use_sim_time: true
