/map_to_odom_static_tf:
  ros__parameters:
    /child_frame_id: odom
    /frame_id: map
    /rotation/w: 1.0
    /rotation/x: 0.0
    /rotation/y: 0.0
    /rotation/z: 0.0
    /translation/x: -5.95
    /translation/y: -9.85
    /translation/z: 0.0
    use_sim_time: false
